projects:
  irisa:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src\API.ts
        docsFilePath: src\graphql
        graphQLApiId: upsw7nqiy5bl3hb4a3ckl77odi
      endpoints:
        prod: >-
          https://tqs5aulffrc2he67xtidapropy.appsync-api.ap-southeast-2.amazonaws.com/graphql
