projects:
  irisa:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src\app\API.service.ts
        docsFilePath: src\graphql
        graphQLApiId: upsw7nqiy5bl3hb4a3ckl77odi
      endpoints:
        prod: >-
          https://sm4dmth2mrawtpurz4xum7vrx4.appsync-api.ap-southeast-2.amazonaws.com/graphql
