projects:
  irisa:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src\API.ts
        docsFilePath: src\graphql
        graphQLApiId: cojacjzofjgtvkrcx6p2eh2wca
      endpoints:
        prod: >-
          https://a7rqkgkj4fhtbjxdfjrdmqgj34.appsync-api.ap-southeast-2.amazonaws.com/graphql
