// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'ap-southeast-2',
    aws_cognito_identity_pool_id: 'ap-southeast-2:6ee302a4-8036-47fd-90c0-6455f4cd75b7',
    aws_cognito_region: 'ap-southeast-2',
    aws_user_pools_id: 'ap-southeast-2_d6cypRasd',
    aws_user_pools_web_client_id: '30aaqa11def8pv48lbg18iu8f9',
    aws_appsync_graphqlEndpoint: 'https://a7rqkgkj4fhtbjxdfjrdmqgj34.appsync-api.ap-southeast-2.amazonaws.com/graphql',
    aws_appsync_region: 'ap-southeast-2',
    aws_appsync_authenticationType: 'AWS_IAM'
};


export default awsmobile;
